### ISSUE TITLE
No Fix.library panics when trying to marshal a nil *time.Time struct member

### ISSUE THREAD

**Issue by Nazozen** [guregu/dynamo#101]
Thank you for creating the Dynamo library !!!
I would not have been able to create an application using DynamoDB without this library.

However, this problem has been partially resolved, but not yet resolved.

I defined such a structure.

type Test structure {
ID int64
Timestamp * time.Time
}

In this case, no error occurs, but add an annotation

type Test structure {
ID int64
Timestamp *time.Time `dynamo:"onothername,omitempty"`
}

I receive a nil pointer reference error as before.

You can also prevent the error by removing the omitempty option.

Copy stack trace when an error occurs.

testing.tRunner.func1 (0xc4201e80f0)
/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go: 711 + 0x2d2
Panic (0x1514cc0, 0xc42004f920)
/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go: 491 + 0x283
time. (* Time) .IsZero (0x0, 0x1597b20)
<autogenerated>: 1 + 0xa9
github.com/guregu/dynamo.isZero (0x1597b20, 0xc4200ecf18, 0x96, 0x1897901)
/Users/makoto/go/src/github.com/guregu/dynamo/encode.go: 433 + 0x4f3
github.com/guregu/dynamo.marshalStruct (0x1543200, 0xc4200ecf00, 0x99, 0x18979c0, 0x1543200, 0x1543200)
/Users/makoto/go/src/github.com/guregu/dynamo/encode.go: 70 + 0x31e
github.com/guregu/dynamo.marshalItem (0x1543200, 0xc4200ecf00, 0x1525b40, 0xc42010fee8, 0x1010414)
/Users/makoto/go/src/github.com/guregu/dynamo/encode.go: 33 + 0xd6
github.com/guregu/dynamo.Table.Put (0x15a174c, 0xc, 0xc42004f8e0, 0x1543200, 0xc4200ecf00, 0xc42004f8e0)
/Users/makoto/go/src/github.com/guregu/dynamo/put.go: 24 + 0x3c

**Comment by guregu** [comment]
Oh no! Thanks for the report. 
I should be able to fix this soon.
In the meantime, feel free to remove `omitempty`, since it gets omitted automatically anyway.

**Comment by guregu** [comment]
I've fixed this issue and released `v1.3.1`. Let me know if you have any problems.

**Comment by Nazozen** [comment]
Thank you!!

I was able to confirm the correction.
