### ISSUE TITLE
SerializationException when inserting list with empty strings

### ISSUE THREAD

**Issue by twbryan** [guregu/dynamo#102]
to reproduce:

`
err = table.Put(struct {
        ID   string
        Test []string
    }{"test", []string{"hi", ""}}).Run()
    if err != nil {
        panic(err)
    }
`

results in:

> panic: SerializationException: status code: 400, request id: <ID>

By dumping the marshalled output, it looks like it's being turned into:

`{
  M: {
    Test: {
      L: [{
          S: "hi"
        },<invalid value>]
    },
    ID: {
      S: "test"
    }
  }
}`

**Comment by gnusosa** [comment]
Any updates on this? This is occurring in our services setup too.

**Comment by guregu** [comment]
So, DynamoDB can't store empty strings.
With the other parts of the library I just automatically omit the empty strings and everything's good.
But if I did that with lists it would mess up the index and lead to bad things happening.

I could either:
1. Return a better error message.
2. Store NULLs instead (which I've successfully avoided in the rest of the library). 

I think this may be one of the legit uses cases of the null type 🤔

**Comment by twbryan** [comment]
I assume NULL would de-serialize back to the empty string, so that seems reasonable to me.

You put "" in, you get "" back out.. ("" is just pronounced NULL in dynamodb-ese :) )

**Comment by guregu** [comment]
Yeah, that's the idea.
It might take a while because I need to make the decoding stuff aware of whether it's a pointer or inside a slice.
This also brings up some questions like: should a DynamoDB NULL translate to a go nil in a []*string? Probably yes.

**Comment by twbryan** [comment]
Maybe as a default duplicate what json.Unmarshal would do? That probably meets the principal of least surprise.

**Comment by guregu** [comment]
Sorry it's taking a while. This is my next major focus.

**Comment by guregu** [comment]
Luckily, DynamoDB supports empty strings now so this is now fixed in the latest version, `v1.9.0`. Sorry for the long wait.
