### ISSUE TITLE
 value method time.Time.MarshalText called using nil *Time pointer

### ISSUE THREAD

**Issue by wolfZX** [guregu/dynamo#105]
Just informing that for `v1.3.0` when adding `omitempty` inside dynamo tag, it will panic and return error `value method time.Time.MarshalText called using nil *Time pointer`

**Example:**
Structure *time.Time `dynamo:"structure,omitempty" json:"structure,omitempty"`

Fix by taking off omitempty
**Example:**
Structure *time.Time `dynamo:"structure" json:"structure,omitempty"`

**Comment by guregu** [comment]
This should already be fixed in v1.3.1. Please upgrade and try again.
https://github.com/guregu/dynamo/releases/tag/v1.3.1

**Comment by wolfZX** [comment]
@guregu Yup, upgraded and tried, it works, thanks!
