### ISSUE TITLE
Using DynamoDB Accelerator

### ISSUE THREAD

**Issue by dolfelt** [guregu/dynamo#108]
Is there any way to use this library with DAX? We're looking for performance gains while keeping all the advantages of using this library.

I'm also happy to contribute if there are ideas on how to accomplish this.

**Comment by guregu** [comment]
I've never tried it, but you might be able to do it like this (see: sample code):
https://qiita.com/stk0724/items/d36f48ad86573ec35d4d

Give it a shot and let me know if it works!

**Comment by guregu** [comment]
FWIW I just tried out DAX with this library and it seems to work fine!
All you have to do is something like:
```go
	cfg := dax.DefaultConfig()
	cfg.HostPorts = ["dax endpoints go here"]
	cfg.Region = "us-west-2"
	client, err := dax.New(cfg)
	if err != nil {
		panic(err)
	}
	db := dynamo.NewFromIface(client)
	// use db like normal
```

**Comment by guregu** [comment]
Going to close this for now but feel free to make a new issue if you notice any DAX problems.
