### ISSUE TITLE
Are there any plans on implementing transactions?

### ISSUE THREAD

**Issue by rcbrandaops** [guregu/dynamo#110]

**Comment by guregu** [comment]
Transactions are fully(?) implemented! 
Check out https://github.com/guregu/dynamo/blob/master/tx_test.go for an example of how to use them.
Due to some AWS SDK issues, we are missing support for CancellationReasons 😭 (see: https://github.com/aws/aws-sdk-go/issues/2318)

**Comment by rcbrandaops** [comment]
Oh 😮 . Hopefully they will do it soon! Thanks for the response, Greg.
