### ISSUE TITLE
Table operations...

### ISSUE THREAD

**Issue by guregu** [guregu/dynamo#12]
- [x] CreateTable
- [x] DeleteTable
- [x] DescribeTable
- [x] UpdateTable

**Comment by guregu** [comment]
Idea from @kyokomi: create a table by providing a struct.

**Comment by suzuken** [comment]
Hi @guregu san, thank you for providing nice library! I wanna this operations on dynamo. 

> create a table by providing a struct.

It looks good idea for me, too. How about using struct tag like https://github.com/naoina/genmai#schema to define hash and range keys. Below is example in genmai.

```go
// The struct "User" is the table name "user".
// The field name will be converted to lowercase/snakecase, and used as a column name in table.
// e.g. If field name is "CreatedAt", column name is "created_at".
type User struct {
    // PRIMARY KEY. and column name will use "tbl_id" instead of "id".
    Id int64 `db:"pk" column:"tbl_id"`

    // NOT NULL and Default is "me".
    Name string `default:"me"`

    // Nullable column must use a pointer type, or sql.Null* types.
    CreatedAt *time.Time

    // UNIQUE column if specify the db:"unique" tag.
    ScreenName string `db:"unique"`

    // Ignore column if specify the db:"-" tag.
    Active bool `db:"-"`
}
```

It's separate `db` and `column` to define it's behavior. It is one of idea to implement hash and range key.

**Comment by guregu** [comment]
Hello @suzuken, thank you for the suggestion. 

I'm thinking either:
```go
type UserAction struct {
	UserID string    `dynamo:"ID" key:"hash"`
	Time   time.Time `key:"range"`
	Seq    int64     `key:"hash" localIndex:"UserID-Seq-index"`
	UUID   string    `key:"hash" index:"UUID-index"`
}
```

or

```go
type UserAction2 struct {
	UserID string    `dynamo:"ID,hashKey"`
	Time   time.Time `dynamo:",rangeKey"`
	Seq    int64     `dynamo:",rangeKey,localIndex=UserID-Seq-index"`
	UUID   string    `dynamo:",hashKey,index=UUID-index"`
}
```

where index is for global secondary indices (much more common than local). 

I think the first one looks nicer so I will probably implement it first, but they could coexist.

**Comment by guregu** [comment]
Hmm, one consideration is fields used in multiple index

Like what if you had a ID primary hash key, a local ID-Seq-index and a global Seq-ID-index... (contrived example, I know). 

Maybe it would be best to put the hash/range info inside the index tag.

```go
type UserAction struct {
    UserID string    `dynamo:"ID" key:"hash" index:"Seq-ID-index,range"`
    Time   time.Time `key:"range"`
    Seq    int64     `localIndex:"ID-Seq-index,rage" index:"Seq-ID-index,hash"`
    UUID   string    `index:"UUID-index,hash"`
}
```

**Comment by suzuken** [comment]
Oh, thank you for early reply (and start implement).  I like this style.

```go
type UserAction struct {
    UserID string    `dynamo:"ID,hash" index:"Seq-ID-index,range"`
    Time   time.Time `dynamo:",range"`
    Seq    int64     `localIndex:"ID-Seq-index,rage" index:"Seq-ID-index,hash"`
    UUID   string    `index:"UUID-index,hash"`
}
```

`dynamo:"ID,hash"` style is align with `localIndex:"ID-Seq-index,rage` style. It's clear. But, is it breaking backward compatibility?

**Comment by guregu** [comment]
@suzuken: backwards compatibility is fine! I added CreateTable with that syntax: #21

**Comment by suzuken** [comment]
That's fine! Thanks!

**Comment by guregu** [comment]
Added DeleteTable too: f7aad4a79275ec4b1744d928de633d0eacd8ab94

**Comment by guregu** [comment]
Finally done with #43.
