### ISSUE TITLE
Cannot create a GSI using the Index function, which seems to have a bug

### ISSUE THREAD

**Issue by domino14** [guregu/dynamo#121]
I have the following type:

```go
type configData struct {
	ID   string `dynamo:"id,hash"`
	Type string `dynamo:"type,range"`
}
```

and I tried creating a table with an index as follows:

```go
            db.CreateTable("config", configData{}).
			OnDemand(true).
			Index(dynamo.Index{
				Name:        "type-gsi",
				HashKey:     "type",
				HashKeyType: dynamo.StringType,
			 	ProjectionType: dynamodb.ProjectionTypeAll,
			}).
			RunWithContext(ctx); err != nil {
			log.Fatal().Err(err).Msg("creating config table")
		}
```

And it gives me this error: ```ValidationException: No Hash Key specified in schema.  All Dynamo DB tables must have exactly one hash key```
However, it works if I replace the `dynamo.StringType` with the string `"HASH"`. The way the library code is written, the HashKeyType should be HASH or RANGE, but the documentation for the `dynamo.Index` structure indicates that `HashKeyType` should be one of the data types. I think this documentation and code are incorrect.

**Comment by guregu** [comment]
Thanks for making the issue. This was a bug in CreateTable.Index. It should be fixed now (please set HashKeyType to dynamo.StringType as per the documentation, not "HASH").
Released v1.6.1 which contains the fix.
