### ISSUE TITLE
Unable to Put with AWSEncoding

### ISSUE THREAD

**Issue by gir** [guregu/dynamo#125]
I am unable to use `Put` with `AWSEncoding`:

```golang
import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/guregu/dynamo"
)

type Foo struct {
	ID string `dynamodbav:"id"`
}

func main() {
	s, err := session.NewSession(&aws.Config{
		Region:   aws.String("us-east-1"),
		LogLevel: aws.LogLevel(aws.LogDebugWithHTTPBody),
	db := dynamo.New(s)

	foo := Foo{
		ID: "bar",
	}
	db.Table("Foo").Put(dynamo.AWSEncoding(foo)).Run()
}
```

Results in:

```
...
{"Item":{},"ReturnValues":"NONE","TableName":"Foo"}
...
```

Looks like this line is eventually hit skipping all marshaling https://github.com/guregu/dynamo/blob/b868cf6054464579dec862d3ae8ecc20a7251946/encode.go#L66

**Comment by guregu** [comment]
Hello, thanks for the bug report! I just released `v1.7.3` which should fix this. Let me know if you have any problems with it.

I added special-casing for the AWSEncoding stuff but in the future I will probably add an interface for encoding/decoding items (instead of just attribute values).
