### ISSUE TITLE
Set ScanIndexForward

### ISSUE THREAD

**Issue by ryudice** [guregu/dynamo#128]
Is there any way to change the ScanIndexForward attribute of the query?

**Comment by guregu** [comment]
Yes, use Order.
https://godoc.org/github.com/guregu/dynamo#Query.Order
https://godoc.org/github.com/guregu/dynamo#Order

```go
const (
    Ascending  Order = true  // ScanIndexForward = true
    Descending       = false // ScanIndexForward = false
)
```
