### ISSUE TITLE
Delete returns true if record ID not present

### ISSUE THREAD

**Issue by deepnirmal** [guregu/dynamo#130]
Following is the statement

`DB.Table("table-name").Delete("ID", id).Run()`

**Comment by guregu** [comment]
That's how DynamoDB works:
> Unless you specify conditions, the DeleteItem is an idempotent operation; running it multiple times on the same item or attribute does not result in an error response.
> https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DeleteItem.html

You can do this:
```go
DB.Table("table-name").Delete("ID", id).If("attribute_exists('ID')").Run()
```
