### ISSUE TITLE
Custom unmarshalling at struct level

### ISSUE THREAD

**Issue by RaeesBhatti** [guregu/dynamo#131]
Allow specification of custom unmarshaller for a struct like so:
```go
type User struct {
	Id		string
	Username	string
	Name		string
}
func (u User) UnmarshalDynamo(av *dynamodb.AttributeValue) error {
	u.Id = "x"
        u.Name = "z"
        u.Username = u.Id + u.Name
	return nil
}
```

If I add the above to a struct being fetched from database using `guregu/dynamo` library, nothing happens. From what I can tell that function is not being executed.
It will be useful to have this kind of unmarshalling to enhance the data coming from database. A similar functionality is implemented in `encoding/json.Unmarshal`

**Comment by guregu** [comment]
Hello,
This recently got added in https://github.com/guregu/dynamo/pull/126

Try using UnmarshalItem.

**Comment by RaeesBhatti** [comment]
That works as expected. Thank you!
