### ISSUE TITLE
If possible, support map[string]T as set where T is struct{}

### ISSUE THREAD

**Issue by finnbear** [guregu/dynamo#132]
Right now, `map[string]struct{}` is supported for marshaling into a set. However, `map[string]Empty` cannot be marshaled into a set:
```go
type MyString string
type Empty struct{} // I prefer using Empty so I can type Empty{} not struct{}{} to initialize one of them

type Struct struct {
    Foo map[MyString]int `dynamo:"s"` // Can be marshaled, into a dynamo map
    Set map[string]Empty `dynamo:"s,set"` // Cannot be marshaled into a dynamo set
}
```
In the same way that `Foo` can be marshaled into a dynamo map, even though its map key type is `MyString` not `string`, `Set` should be able to be marshaled into a dynamo set even though its map value type is `Empty` not `struct{}`.

**Comment by guregu** [comment]
Merged #132!
