### ISSUE TITLE
Using interface types

### ISSUE THREAD

**Issue by Deewai** [guregu/dynamo#134]
Is it possible to do something like this with this package?

`type Game struct{`
`ID string`
`Active bool`
`Details interface{}`
`}`

`type FootBall struct{`
`Home string`
`Away string`
`}`
Then when creating an item, 
`item := Game{ID: "", Active: false, Details: FootBall{Home:"Arsenal", Away:"Chelsea"}}`
`table.Put(item)`

Will this work,?
Do i need to implement the Marshaler and Unmarshaler interface?

**Comment by guregu** [comment]
That should work. You don’t need to implement the interfaces unless you want to customize it.
Keep in mind that DynamoDB can’t store blank strings so in your example the ID field will be automatically omitted.

**Comment by Deewai** [comment]
Okay, thanks. The id field actually has a value, I just skipped it for simplicity sake
