### ISSUE TITLE
omitempty is handled differently than encoding/json for TextMarshaler

### ISSUE THREAD

**Issue by finnbear** [guregu/dynamo#145]
Here's how `encoding/json` handles the `omitempty` tag: https://play.golang.org/p/2URUoO7aa-H
```go
package main

import (
	"encoding/json"
	"fmt"
)

type Foo int

func (foo Foo) MarshalText() ([]byte, error) {
	return []byte("hello"), nil
}

type Bar struct {
	Foo Foo `json:",omitempty"`
}

func main() {
	bar := Bar{Foo: 0}
	buf, err := json.Marshal(bar)
	fmt.Println(string(buf), err)
}
```

Outputs: `{} <nil>`

If `bar := Bar{Foo: 5}`, outputs: `{"Foo":"hello"} <nil>`

As you can see, despite the `MarshalText()` function returning a non empty string, the `bar.Foo` is omitted because `0` is the zero-value for the underlying type `int`. It seems that in your library, the output of the `MarshalText()`'s length is what determines whether a value is omitted.

While I actually prefer your approach over that of `encoding/json`, I would like some way to achieve consistency between the two. One way to do this would be for you to implement an `omitzero` tag which would strictly omit zero values of an underlying type according to `reflect.IsZero` or something.

**Comment by guregu** [comment]
Hmm, our `omitempty` is already a lot different from json's so it would take a lot to reach parity.
Ours respects `IsZero() bool` methods so one way you could solve this is add:
```go
func (foo Foo) IsZero() bool {
   return foo == (Foo{})
}
```

It would totally be possible add `omitzero` but I'm not sure if I want to add yet another omit flag.
I'm not opposed to it though. 🤔
