### ISSUE TITLE
Example of Query.All using AWS encoded struct

### ISSUE THREAD

**Issue by ryan-timothy-albert** [guregu/dynamo#147]
Hi @guregu. Thanks for the work on the package, really enjoying using it so far. Currently I am running into one issue. 

I am using dynamodbav in my models

When getting one item using `.One(dynamo.AWSEncoding(&model))` is working well for me.

However, when trying to get more than one item at a time AWS encoding is not working for me. Is it possible to use query.All with AWS encoded structs.

**Comment by guregu** [comment]
Hello, sorry about that. I'll double check and add support for it soon.
In the meantime, something like this should work:

```go
iter := table.Scan().Iter()
var all []Model
var m Model
for iter.Next(dynamo.AWSEncoding(&m)) {
	// if m is a pointer, might need to do this so you don't add the same thing over and over:
	// copied := *m
	// m = &copied
	all = append(all, m)
}
return all, iter.Err()
```

Anyway, I'll take a look soon.

**Comment by guregu** [comment]
I added support for `.All(dynamo.AWSEncoding(&slice))` in the latest version, v1.10.0, so the workaround shouldn't be necessary anymore.
https://github.com/guregu/dynamo/tree/v1.10.0

Let me know if you have any issues.

**Comment by ryan-timothy-albert** [comment]
Thanks for the incredibly prompt response!
