### ISSUE TITLE
Is batch write concurrency safe?

### ISSUE THREAD

**Issue by AnhTaFP** [guregu/dynamo#149]
Hi, 

I am wondering if the batch write operation is safe for concurrency? More specifically, this is somewhat I'm trying to do
```
        db := dynamo.New(...)

	for i := 0; i < 5; i++ {
		go func() {
			db.Table("my-table").Batch().Write().Put(data...).Run()
		}()
	}
```

I am using version 1.5.1
I'd really appreciate your help. Thank you for a very nice lib!

**Comment by guregu** [comment]
Hello, thanks!

Your code should be fine. It’s thread-safe to run multiple requests on the same dynamo.DB.

BTW, you might want to upgrade your version.

**Comment by AnhTaFP** [comment]
@guregu thank you very much, I'll close the issue :)
