### ISSUE TITLE
ValidationException: One or more parameter values were invalid: Missing the key userID in the item

### ISSUE THREAD

**Issue by dushyantSingh** [guregu/dynamo#155]
Hi,
I am facing this problem when I am trying to save data in dynamodb. Here is the code

`db := dynamo.New(session.New(), &aws.Config{Region: aws.String("ap-southeast-1")})
 dayPlanTable = db.Table("SL_DAY_PLAN")
 if err := dayPlanTable.Put(dayPlan).Run(); err != nil {
		log.Printf("Saving error %v", err)
 }
`
This is the structure for dayPlan used above
type Response struct {
	DayPlanID string `json:"planID"`
	UserID string `json:"userID"`
	Date string `json:"date"`
}

JSON string from dayPlan is 
`{
    "planID": "planID_1000001",
    "userID": "user_11122000",
    "date": "2021-01-28"
}`

**Comment by guregu** [comment]
Hi. This library doesn't look at the `json` tags. Please add the `dynamo` tag.
```go
	type Response struct {
		DayPlanID string `json:"planID" dynamo:"planID"`
		UserID    string `json:"userID" dynamo:"planID"`
		Date      string `json:"date" dynamo:"planID"`
	}
```

**Comment by dushyantSingh** [comment]
Thanks that solved the problem  🥇
