### ISSUE TITLE
update.Append("path_to_list", string|TextMarshaler) results in ValidationException

### ISSUE THREAD

**Issue by finnbear** [guregu/dynamo#156]
I am trying to append a `TextMarshaler` to a Dynamo List, using the `v1.10.2` version of this package:
```go
update = db.userTable.Update("userID", userID)
update.Append("createdSceneIDs", sceneID) // sceneID implements MarshalText()
return update.Run()
```
When running this update, I get the error:
```console
ValidationException: Invalid UpdateExpression: Incorrect operand type for operator or function; operator or function: list_append, operand type: S
	status code: 400, request id: BG5TV7KSE9IAUSSKAK7AFBT7NFVV4KQNSO5AEMVJF66Q9ASUAAJG
```
I tried changing `sceneID` to `"foo"` and the issue persisted, so I don't think it is unique to `TextMarshaler`.

Here is what `createdSceneIDs` looks like in my table:
![image](https://user-images.githubusercontent.com/20015102/108294193-41c6d380-714a-11eb-8030-413faa479383.png)

**Comment by guregu** [comment]
list_append only takes lists as parameters, try passing `[]foo{sceneID}`

Should definitely document that better or automatically stick non-lists into a list though.

**Comment by finnbear** [comment]
Thank you very much for this package and your quick answer, which should absolutely solve my problem. You're right that your documentation isn't clear about this, though.
