### ISSUE TITLE
bool fields are ignored

### ISSUE THREAD

**Issue by finferflu** [guregu/dynamo#163]
Hi,

I have the following sample code:

```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/guregu/dynamo"
)

type DeploymentLog struct {
	AppType        string            `dynamo:"deploymentId"`
	DeploymentInfo string            `dynamo:"deploymentInfo"`
	Environment    string            `dynamo:"env"`
	isFeature      bool              `dynamo:"isFeature"`
	isDeployed     bool              `dynamo:"isDeployed"`
	Metadata       map[string]string `dynamo:"metadata"`
	Timestamp      int               `dynamo:"timestamp"`
	VersionID      string            `dynamo:"versionId"`
}

func main() {
	sess, err := session.NewSession(&aws.Config{
		Region:      aws.String("eu-west-1"),
		Credentials: credentials.NewStaticCredentials(os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), ""),
	})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	db := dynamo.New(sess)
	table := db.Table("deployments_mock")

	d := DeploymentLog{
		AppType:        "api",
		DeploymentInfo: "v_4:staging",
		Environment:    "staging",
		isFeature:      true,
		isDeployed:     false,
		VersionID:      "v_4",
		Metadata: map[string]string{
			"someId": "56456",
		},
		Timestamp: int(time.Now().Unix()),
	}

	err = table.Put(d).Run()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

Everything seems to work well, however, both fields `isFeature` and `isDeployed` never get populated. I've tried the following:

- Set them to `true`
- Set them to `false`
- Change the fields type to `string` and set them to either `"true"` or `"false"`

Nothing seems to work so far and I'm at loss. I've read through the documentation, the issues, and some of the source code, and in theory, this should just work. Am I missing anything?

For reference, this is the created item:

```json
{
  "deploymentId": {
    "S": "api"
  },
  "deploymentInfo": {
    "S": "v_4:staging"
  },
  "versionId": {
    "S": "v_4"
  },
  "metadata": {
    "M": {
      "someId": {
        "S": "56456"
      }
    }
  },
  "env": {
    "S": "staging"
  },
  "timestamp": {
    "N": "1619113031"
  }
}
```

Thanks!

**Comment by guregu** [comment]
Hello,
If you make them start with a capital letter it should work:
```go
type DeploymentLog struct {
	// ...
	IsFeature      bool              `dynamo:"isFeature"`
	IsDeployed     bool              `dynamo:"isDeployed"`
}
```

This is an inherent limitation in Go. Uncapitalized fields become private and are unable to be accessed by reflection† (and thus, this library).


† Technically, you can read them but not write them. It's standard practice to ignore them, for example the `encoding/json` standard library package works the same way. You can embed private types with public fields and it'll work though.

**Comment by finferflu** [comment]
@guregu,

Was about to post that `Deployed` in place of `isDeployed` worked, so thanks for the explanation. I think it might be useful to add that detail to the docs to avoid other people getting confused.

**Comment by guregu** [comment]
Added some stuff to the readme about this, thanks!

**Comment by finferflu** [comment]
Thanks @guregu, I've taken a look at your last commit and the docs are so much clearer now!
