### ISSUE TITLE
Part of partition key is marshalled to *** when putting item

### ISSUE THREAD

**Issue by qinjin** [guregu/dynamo#172]
Hi, we've met a strange issue on putting item. The beginning of the partition key is marshalled to `***`...

Here is the struct of the DB item:
```
        type dbValue struct {
	        NamespaceAndPartitionKey string `dynamo:"namespace_and_partitionKey,hash" index:"namespace-index,hash"`
	        SortKey                 string `dynamo:"sort_key,range"`
	        Data                    []byte `dynamo:"data"`
        }
```

We marshal and print it before calling `Put` item on `dynamoTable`.
```
	value := dbValue{
		NamespaceAndPartitionKey: "test_parition_key",
		SortKey:                 "test_sort_key",
		Data:                      []byte("abc"),
	}
	marshalledValue, err := dynamo.Marshal(value)
	if err != nil {
		fmt.Println(fmt.Errorf("error on marshalling %w", err))
	}
	fmt.Printf("marshalled dbValue struct: %+v", marshalledValue)

	return s.dynamoTable.Put(value).Run()
```

From logs, we can see that the partition key was marshalled to `***_and_partitionKey`.
```
marshalled dbValue struct: {
   M: {
    ***_and_partitionKey: {
      S: "test_parition_key"
    },
    sort_key: {
      S: "test_sort_key"
    },
    data: {
      B: <binary> len 3
    }
  }
```

Any insights on what could lead to this unexpected asterisks?

**Comment by guregu** [comment]
That's quite strange indeed. Are you sure your logs aren't getting censored? (Maybe overzealous security?)
I can't think of anything in this library that would be causing that.
Here's the code for the part that determines the name for attributes:
https://github.com/guregu/dynamo/blob/c8877256c9694747def29c1de6662b4768c29fea/encode.go#L611-L619
