### ISSUE TITLE
Incrementing a value

### ISSUE THREAD

**Issue by maxisme** [guregu/dynamo#175]
Hello,

How would you recommend I do something like [this](https://stackoverflow.com/a/57935816/2768038) with this library:
```
dynamoDB.updateItem({
  TableName: "Users",
  Key: { "UserId": { S: "c6af9ac6-7b61" } },
  ExpressionAttributeValues: { ":inc": {N: "1"} },
  UpdateExpression: "ADD loginCount :inc"
})
```

I am currently fetching the row getting the value then adding 1 to it but I am worried about race conditions.

**Comment by shimonmagal** [comment]
That is supported. Just do:

`session.Table("tableName").Update("hashKeyName", hashKeyValue).Add("fieldToUpdate", 1).Run()`
