### ISSUE TITLE
TransactWriteItemsRequest support

### ISSUE THREAD

**Issue by DirectorStellaris** [guregu/dynamo#179]
I founded dynamo didnt has api use TransactWriteItemsRequest when I have a transaction needs
 
Will dynamo add TransactWriteItemsRequest in future？
Or we had a solution on transaction

**Comment by BrianLeishman** [comment]
I think you're looking for this https://pkg.go.dev/github.com/guregu/dynamo@v1.11.0#WriteTx

**Comment by guregu** [comment]
Yep, use `db.WriteTx()`.
