### ISSUE TITLE
Question regarding marshaling of third-party types

### ISSUE THREAD

**Issue by mlafeldt** [guregu/dynamo#195]
Hey @guregu, this might be a foolish question, but is there any way to add custom marshaling for a type defined in a third-party package without having to modify that package (and e.g. implementing the `Marshaler` interface) or re-implementing `MarshalItem`?

In order to convert JS values from https://github.com/robertkrimen/otto into DynamoDB attributes, I'm currently using a modified version of https://github.com/guregu/dynamo/blob/master/encode.go that adds support for `otto.Value`:

```go
func marshal(v interface{}, flags encodeFlags) (*dynamodb.AttributeValue, error) {
// ...

	switch x := v.(type) {
// ...
	case otto.Value:
		val, err := x.Export()
		if err != nil {
			return nil, err
		}
		return marshal(val, flags)
	}
	return marshalReflect(rv, flags)
}
```

Of course, that's not ideal. 😄 

AFAIK, it's not possible to implement an interface for types defined in third-party packages, but maybe you have some other idea I'm not aware of?

**Comment by guregu** [comment]
Hello, I think it's a good question. Currently there isn't an easy way to do this. It's a problem the standard library encoding packages have as well.

There's an interesting accepted proposal for better customization of marshalers:
https://github.com/golang/go/issues/5901#issuecomment-907696904

If we implemented an API like this then we could support lots of cool use cases. I am not sure exactly how it works internally though, or if there's any implementation code available, need to do some digging.

The only way to solve this currently is to wrap the object and implement `MarshalDynamo` etc, but of course if you don't control the call site you can't wrap it :)

**Comment by mlafeldt** [comment]
Thanks for the link and more context. Will follow along. Being able to register bespoke marshalers sounds like a good compromise.

In the meantime, I found another library that doesn't require custom marshaling. :)
