### ISSUE TITLE
allowemptyelem for nested maps and collections

### ISSUE THREAD

**Issue by veedubyou** [guregu/dynamo#199]
Hi, firstly thanks for the great library.

I wanted to see if there was a way to apply the allowemptyelem in a nested way. Right now allowemptyelem only applies to the first level of its elements. I try to demonstrate this behaviour in this code:

```
package main

import (
	"fmt"
	"github.com/guregu/dynamo"
)

type Foo struct {
	Fields map[string]interface{} `dynamo:",allowemptyelem"`
}

func main() {
	innerChild := map[string]interface{}{
		"FirstLevelNestedChildren": map[string]interface{}{
			"SecondLevelChildren": "",
		},
		"FirstLevelUnnestedChildren": "",
	}

	testObj := Foo{Fields: innerChild}
	if marshaledOutput, err := dynamo.Marshal(testObj); err == nil {
		_, ok := marshaledOutput.M["Fields"].M["FirstLevelNestedChildren"].M["SecondLevelChildren"]
		// expect true, but is false
		fmt.Println(ok)

		_, ok = marshaledOutput.M["Fields"].M["FirstLevelUnnestedChildren"]
		// expect true, and is true
		fmt.Println(ok)
	} else {
		panic(err)
	}
}
```

My usecase is to marshal a map of arbitrary shape, but still preserve the empty values. There doesn't seem to be a way to specify this behaviour right now.

(I've found that the behaviour probably happens around here: https://github.com/guregu/dynamo/blob/a9acd46de9766ea293a410ced44b51268d5b3bfa/encode.go#L288 where the flag to allow empty elems is not perpetuated down when drilling in)

Is this an unintended bug or the intended design of the API? If it's intended, would you consider adding a capability for this nested case? Happy to help with making the PR if this is in line with the library's design.

**Comment by guregu** [comment]
Hello, thanks for the detailed report and kind words.
I'd classify this as a bug. `allowemptyelem` is a bit of an afterthought: when this library was originally made it was impossible to save empty strings, so it got tacked on later.
I think you could fix it from the place you linked (probably, sorry, it's a bit of a mess). I'm totally OK with it cascading down to child elements. Let's just make sure it doesn't do anything unexpected, which the tests should catch I hope.

Feel free to make a PR, it would be appreciated.

**Comment by veedubyou** [comment]
Sounds good! Will put it up soon.
