### ISSUE TITLE
Parallel Scan

### ISSUE THREAD

**Issue by guregu** [guregu/dynamo#20]
Allow the use of multiple segments in a Scan operation.
See: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#QueryAndScanParallelScan

Shouldn't be too hard... although figuring out how to wrangle Iter and parallel scans may be difficult.

**Comment by lixw1994** [comment]
Excited waiting!

**Comment by sergiomendoncadh** [comment]
+1

**Comment by guregu** [comment]
I implemented this in #219 but I need to test it a bit more before merging. Feel free to give it a try.

**Comment by guregu** [comment]
Just released in [v1.20](https://github.com/guregu/dynamo/releases/tag/v1.20.0).
