### ISSUE TITLE
DB does not implement all the functions of DynamoDBAPI interface

### ISSUE THREAD

**Issue by SebastienMelki** [guregu/dynamo#205]
This is preventing us from using this client as a dynamodbiface.DynamoDBAPI. Am I doing something wrong or is this as expected?

![image](https://user-images.githubusercontent.com/5787993/200397136-754dac9d-27b9-4d9f-8b01-ca0b6d37ea1d.png)

**Comment by guregu** [comment]
`*dynamo.DB` doesn't implement `dynamodbiface.DynamoDBAPI`. That is the low-level API from the AWS SDK. If you want to use that, you don't need this library. This library is a higher level interface built on top of that.
