### ISSUE TITLE
I can not get the effective lastEvaluatedKey by LastEvaluatedKey()

### ISSUE THREAD

**Issue by BaiMoHan** [guregu/dynamo#207]
I want to do pagination.
I write these code, but I get empty lastEvaluatedKey and there are 25 items in my tables in fact
```go
        var userList []model.DynamodbUser
	offset := (page - 1) * pageSize
	var viewList []api_info.UserView
	count := 0

	lastEvaluatedKey := global.UserTable.Scan().SearchLimit(offset).Iter().LastEvaluatedKey()

	log.Debug(operationId, "offset=", offset, " last=", lastEvaluatedKey)

	err := global.UserTable.Scan().StartFrom(lastEvaluatedKey).Limit(pageSize).All(&userList)
   // ...
```
However, log shows the lastEvaluatedKey is empty and userList has unexpected data.
Then, I write these code and it works.
```go
        var userList []model.DynamodbUser
	offset := (page - 1) * pageSize
	var viewList []api_info.UserView
	count := 0

	var oldUserList []model.DynamodbUser
        // in fact, I do not want to get the previous items
	lastEvaluatedKey, err2 := global.UserTable.Scan().SearchLimit(offset).AllWithLastEvaluatedKey(&oldUserList)
	if err2 != nil {
		log.Error(operationId, err2.Error())
		return []api_info.UserView{}, 0, err2
	}

	log.Debug(operationId, "offset=", offset, " last=", lastEvaluatedKey)

	err := global.UserTable.Scan().StartFrom(lastEvaluatedKey).Limit(pageSize).All(&userList)
```
May I user the api correctly?
Please help me.

**Comment by guregu** [comment]
Hello, there is no such thing as offset-based pagination in DynamoDB. You can't pass StartFrom an arbitrary number, it needs to match a LastEvaluatedKey. In the low-level DynamoDB API, StartFrom corresponds to: [ExclusiveStartKey](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-ExclusiveStartKey). Also, SearchLimit constrains the amount of records checked in a Scan/Query/etc, and if you pass it a 0 I'm guessing it returns no results, but I've never tried it before. 

The second snippet is more correct. You need to get the LastEvaluatedKey from Scan and pass it to StartFrom to get the "next page". If you were making a website, for example, you would send the LastEvaluatedKey to the user as part of the link to the next page. It's just a DynamoDB map, so you can JSON+Base64 encode it with the Go standard library to turn it into a string, same with decoding.

**Comment by BaiMoHan** [comment]
I got it!
Thank you for teaching me!
I have known how to do it. You are right. I should send the LastEvaluatedKey to the user as part of the link to the next page.
Thank you very much!
