### ISSUE TITLE
Query on Global Secondary Index

### ISSUE THREAD

**Issue by nightlord189** [guregu/dynamo#214]
Hello! How can i Query table by Global Secondary Index (GSI) with this library?

For example: i have a table with partition key "hash_id" and sort key "range_id". I am creating GSI with partition key "email" and sort key "product_id". I want to Query (not scan) all rows from table with email = "test@user.com" (Query by GSI.partition_key) and i don't want to use partition key of all table. I could do this with AWS UI (see screen), but is it possible with library?

![image](https://user-images.githubusercontent.com/16045193/219365951-dc77e594-94a0-4429-9e65-e8e3e167ae50.png)

**Comment by guregu** [comment]
Yes, you can use the `Query.Index` method to do this.
Something like:

```go
table := db.Table("my-table")
var results []someResultDatatype
err := table.Get("email", "abc@example.com").Index("email-product_id-index").All(&results)
```

You can also use `.Range` to specify how to search against the sort key. The above example will get everything related to that particular email.
