### ISSUE TITLE
Typo in Keys example code

### ISSUE THREAD

**Issue by dharkness** [guregu/dynamo#215]
There's a typo in the example code for the `Keys` interface. The same typo appears in `BatchGet` as well.

```go
// Keys provides an easy way to specify the hash and range keys.
//	table.Batch("ID", "Month").
//		Get([]dynamo.Keys{{1, "2015-10"}, {42, "2015-12"}, {42, "1992-02"}}...).
//		All(&results)
type Keys [2]interface{}
```

This code produces an error that `[]Keys cannot be used for []Keyed`. Should this code actually work? I've tried with Go 1.16 and 1.18.

In my own code, I create an array and assign each key in a loop because the list is dynamic, and in that case using `[]Keyed` as the array type works since I'm assigning each key as `Keys`.

```go
keys := make([]dynamo.Keyed, len(ids))
for i, id := range ids {
	keys[i] = dynamo.Keys{id, "profile"}
}
```

**Comment by guregu** [comment]
Ah sorry, the example code is just wrong. 

It should be:
```go
table.Batch("ID", "Month").
	Get(dynamo.Keys{1, "2015-10"}, dynamo.Keys{42, "2015-12"}, dynamo.Keys{42, "1992-02"}).
	All(&results)
```

This should work as well:
```go
keys := []dynamo.Keyed{dynamo.Keys{1, "2015-10"}, dynamo.Keys{42, "2015-12"}, dynamo.Keys{42, "1992-02"})}
table.Batch("ID", "Month").
	Get(keys...).
	All(&results)
```

You can also do this:

```go
batch := table.Batch("foo", "bar").Get()
for _, id := range ids {
	batch.And(dynamo.Keys{id, "profile"})
}
```

I think the batch API is kind of clunky. If there's any API I want to change in v2 it's the batch stuff.

**Comment by guregu** [comment]
Fixed in https://github.com/guregu/dynamo/commit/e68275cd9ebb270ba7c4fe7e9d9671d84192eb7f
