### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chyi-code** [guregu/dynamo#220]
When the global table is used and Replicas are created, then the LocalSecondaryIndexes returned by the describe table does not have the ARN attribute.

<img width="376" alt="image" src="https://github.com/guregu/dynamo/assets/8390018/72c2566c-0688-4989-bd94-a49fb7f09080">

describetable.go:154 will throw an error.

<img width="636" alt="image" src="https://github.com/guregu/dynamo/assets/8390018/dc18c794-0387-4ff3-9f31-bed55a0d7ea2">

**Comment by guregu** [comment]
Thanks for the report, I'll take a look 👀

**Comment by guregu** [comment]
Just released `v1.20.2` which should fix this.
Thanks again, sorry it took me a while to see this.
