### ISSUE TITLE
Scan All Repeats First Element

### ISSUE THREAD

**Issue by toneill818** [guregu/dynamo#228]
As of 1.22 when running `table.Scan().All(&mySlice)` it populates the correct number of items, but they are all the same. The same code running 1.21 does not have this issue.

**Comment by amit-evermile** [comment]
Happens to me too

**Comment by akmaljalilov** [comment]
It happens to me, too.

**Comment by guregu** [comment]
Hello everyone. I'm very sorry for the breakage. I have just released v1.22.1 which should fix this. Please try it out and let me know how it goes. (Apologies as well for not seeing this earlier -- I have no idea why GitHub isn't notifying me anymore 😢)
