### ISSUE TITLE
Batch Get making multiple calls even for smaller batches

### ISSUE THREAD

**Issue by lzrf0cuz** [guregu/dynamo#240]
Given the below input, Batch Get makes multiple calls even when the number of `dynamo.Keys` are less than 100. They were tested with two `dynamo.Keys`, where the first set exists and the second doesn't.

`[]dynamo.Keys{{mockPKValue1, mockSKValue1}, {mockPKValue2, mockSKValue2}}` There are 2 sets here. When the `BatchGet.All` method is executed, 2 separate calls are made even though the keys belong to the same table and the batch size is only 2.

Adding `in.RequestItems[table] = kas` after line 234 in [https://github.com/guregu/dynamo/blob/master/batchget.go#L234](https://github.com/guregu/dynamo/blob/master/batchget.go#L234) seems to mitigate it. 

I encountered this after migrating to V2.

**Comment by guregu** [comment]
Nice catch, thanks. In v1 the KeysAndAttributes SDK type is a pointer so that's probably where the issue came from. I'll take a look

**Comment by guregu** [comment]
Just released v2.0.2 including this fix, thanks!

Note to self: add request count test after #238 is implemented
