### ISSUE TITLE
Feature Request: support `ReturnValuesOnConditionCheckFailure`

### ISSUE THREAD

**Issue by extemporalgenome** [guregu/dynamo#245]
The write operations which support `ReturnValues` (PutItem, UpdateItem, DeleteItem, transactional equivalents thereof, and possibly others) generally also support `ReturnValuesOnConditionCheckFailure`, which can take a value of `ALL_OLD` to get a strongly consistent read for free (in terms of capacity cost) even if the write was semantically rejected.

This is pretty useful from an atomics perspective, i.e. inspecting the item in a guaranteed state to find out _why_ the condition check failed, all without needing to perform a potentially racing followup read.

Here is a non-complete list of the operations that support this (at least the ones I care most about), and the relevant docs/code:

| Operation  | Docs | SDK V1 | SDK V2 |
|------------|------|--------|--------|
| PutItem    | [link](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#DDB-PutItem-request-ReturnValuesOnConditionCheckFailure) | [link](https://github.com/aws/aws-sdk-go/blob/37d771a/service/dynamodb/api.go#L20562-L20568) | [link](https://github.com/aws/aws-sdk-go-v2/blob/1d44177adda2c58035abe5f2e878c5c5a60db913/service/dynamodb/api_op_PutItem.go#L228-L234) |
| UpdateItem | [link](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ReturnValuesOnConditionCheckFailure) | [link](https://github.com/aws/aws-sdk-go/blob/37d771a/service/dynamodb/api.go#L27222-L27228) | [link](https://github.com/aws/aws-sdk-go-v2/blob/1d44177adda2c58035abe5f2e878c5c5a60db913/service/dynamodb/api_op_UpdateItem.go#L203-L209) |
| DeleteItem | [link](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DeleteItem.html#DDB-DeleteItem-request-ReturnValuesOnConditionCheckFailure) | [link](https://github.com/aws/aws-sdk-go/blob/37d771a/service/dynamodb/api.go#L12388-L12394) | [link](https://github.com/aws/aws-sdk-go-v2/blob/1d44177adda2c58035abe5f2e878c5c5a60db913/service/dynamodb/api_op_DeleteItem.go#L195-L201) |

**Comment by guregu** [comment]
Oh nice, I didn't know this existed (is it new?). I will add it for sure.

**Comment by guregu** [comment]
PR here: #246. Wasn't sure whether it was better to have an API that works based off the errors or another method on the operations so I did both :-)
Let me know if it looks good.

**Comment by guregu** [comment]
Just released in [v2.2.0](https://github.com/guregu/dynamo/tree/v2.2.0). Let me know if you run into any issues

**Comment by extemporalgenome** [comment]
Thanks!
