### ISSUE TITLE
Question: How to Scan/Query by filtering a Map?

### ISSUE THREAD

**Issue by roylee0704** [guregu/dynamo#25]
For instance, take following schema:
```js
{
   id: 1,
   meta: {
      distance: 10   
   }
}
```

How do I scan/query with a filter: `distance > 1`.

Here's what I have tried:
```go
t.Scan().Filter("'meta.distance' > ?", 1)
```

**Comment by roylee0704** [comment]
Ah, I managed to get it working:

```go
t.Scan().Filter("?.distance > ?", "meta", 1)
```

**Comment by guregu** [comment]
Hello, sorry for the late reply. I think either `meta.distance` or `'meta'.distance` should work. Meta doesn't seem to be a reserved word, so if either of them are broken it is a bug.
You can actually put dots in DynamoDB attribute names, so `'meta.distance'` is referring to a top-level value called `meta.distance`, not a child value.
