### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by qzaidi** [guregu/dynamo#27]
Would it be possible to add context, enabling cancellations. go-aws-sdk supports this, and in case when the dynamodb servers are unavailable or latency is high, this would be useful.

We could add a context argument to Run, e.g. RunWithContext(ctx) - would you be open to a patch?

**Comment by guregu** [comment]
Yes, this is a good idea. I think RunWithContext would solve the problem in a nice way.

**Comment by qzaidi** [comment]
#31 - added a pull request.

**Comment by guregu** [comment]
Added, thanks!
