### ISSUE TITLE
Support for marshalling arrays

### ISSUE THREAD

**Issue by patrick91** [guregu/dynamo#33]
Hi! I was trying to use this library to store/read some tweets on dynamo db but it fails when it tries to unmarshal a tweet:

```
2017/06/07 21:17:36 dynamo: can't unmarshal to type: twitter.Indices ([0 0])
```

The twitter.Indices type is this:

```go
// Indices represent the start and end offsets within text.
type Indices [2]int
```

I tried to have a look at the code to make a PR but I'm still a newbie with go. I was wondering if it is possible to add support for arrays?  :)

**Comment by guregu** [comment]
Hello, thank you for the report. It should be totally possible to add support for arrays and I'll do so ASAP.

**Comment by guregu** [comment]
I've fixed it in this commit, let me know if it's still broken. ab45050048293bb6e8fd5fd9090914813eba73d4

**Comment by patrick91** [comment]
Haven't tested it yet (I'm running a fork with some custom changes). Thanks by the way :)
