### ISSUE TITLE
DB uses DynamoDB instead of DynamoDBIFace && client is private

### ISSUE THREAD

**Issue by gaffo** [guregu/dynamo#46]
This prevents mocking or supplying a different dynamo object.

**Comment by guregu** [comment]
Thanks for the issue, I added a new function `NewFromIface` that takes a `dynamodbiface.DynamoDBAPI`. I also added `DB.Client()` to grab a DB's internal client.

**Comment by gaffo** [comment]
Sweet, thanks!
