### ISSUE TITLE
Can only have one global secondary index on a column

### ISSUE THREAD

**Issue by gaffo** [guregu/dynamo#49]
I have a situation where I need to put a Hash only GSI on a column, and also a GSI with the same column as a range key eg:

type Record struct {
	OwnerID string `dynamo:"o,hash"`
	ID      string `dynamo:"i,range" index:"IDX-id,hash" index:"IDX-pd,range"`
	PD     string `dymamo:"pd" index:"IDX-pd,hash"`
}

However the tags in golang seem to collide when you have multiples of the same name, so the hash on IDX-id gets clobbered. If this is in fact what's happening, exposing the index apis seems like a good short term, and exposing a multi-index syntax seems like a good long term.

Let me know if I'm doing this wrong.

**Comment by guregu** [comment]
Thanks for the issue! Just pushed 9834ac3 which I hope takes care of it.

* You can now specify multiple indexes using duplicate struct tags like your example.
* Added CreateTable.Index method to manually specify indexes to add to the new table. 

Caveat: I don't have time to write proper tests today. Please take a look at it and see if it works for you. I'll add more tests soon.

**Comment by guregu** [comment]
Should be taken care of, let me know if you have any issues.
