### ISSUE TITLE
Add consumed capacity to read and write operations

### ISSUE THREAD

**Issue by tamccall** [guregu/dynamo#56]
Read and write operations return a consumed capacity field that describes how much of the table capacity has been consumed during the operation. This can be useful in scenarios where the operations need to be throttled.

Suggestion is to add a method to all table operations called `ConsumedCapacity` where the client can pass a variable to store the output in.

```go
var dog dogs.Dog
var consumed dynamodb.ConsumedCapacity
err := t.Get("OwnerID", owner.ID).
	Index(dogs.OwnerIndex).
	Range("Name", dynamo.Equal, name).
	ConsumedCapacity(&consumed).
	One(&dog)
```

**Comment by guregu** [comment]
I've added support for this in  1f756ee, the API is pretty much just as proposed but I added a `ConsumedCapacity` type to dynamo with less pointers. I will close this for now but please re-open it if you have any ideas or suggestions.
