### ISSUE TITLE
X-Ray tracing for DynamoDB client

### ISSUE THREAD

**Issue by uded** [guregu/dynamo#58]
It would be beneficial to be able to trace DynamoDB calls with X-Ray, as it provides a hell lot of useful insights into how your code is performing. We're using X-Ray with newly announced Go support for Lambda's, and with this library _hiding_ DynamoDB client initialization it's [difficult to wrap it](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-awssdkclients.html) up easily without modifying the code.

My suggestion would be to either made a different implementation to initialize the client *or* to provide a constructor that will take initialized DynamoDB client as a parameter (maybe there is one, but I couldn't find it)

**Comment by guregu** [comment]
Hello, apologies for not seeing this earlier.

You can pass a pre-initialized `*dynamodb.DynamoDB` to this package with [`dynamo.NewFromIface`](https://github.com/guregu/dynamo/blob/master/db.go#L27).

Additionally, there is a very ugly way to grab the current Client (assuming you are not using a mocked out interface). I haven't testing this but it'll probably work:

```go
import (
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-xray-sdk-go/xray"
	"github.com/guregu/dynamo"
)

func main() {
	db := dynamo.New(...)
	client := db.Client().(*dynamodb.DynamoDB).Client
	xray.AWS(client)
}
```

**Comment by uded** [comment]
Found it in the meantime, but got some strange results from this implementation - X-Ray in Go seems a bit unstable IMHO...

Will update if I will discover the reason for my issues. For now happy if this is closed...

**Comment by johan1252** [comment]
@uded @guregu Did either of you get x-ray to work properly with this library? From what I can see, the library would need to provide `withContext` versions of each method to allow x-ray to work properly.

**Comment by johan1252** [comment]
> @uded @guregu Did either of you get x-ray to work properly with this library? From what I can see, the library would need to provide `withContext` versions of each method to allow x-ray to work properly.

Following up on this...
I was able to get this to work in the end. Found that there were WithContext methods provided in https://github.com/guregu/dynamo/pull/31. Using those along with the client instrumentation above I was able to trace calls successfully.
