### ISSUE TITLE
Pagination question

### ISSUE THREAD

**Issue by ghost** [guregu/dynamo#59]
Hi, how can I use this library to expose the lastEvaluatedKey to the client and let the client incrementally paginate through? thanks a lot for your help

**Comment by guregu** [comment]
Hello, currently I don't have a good way to do this, sorry. I will add it soon. 
If you are iterating through a hash+range table, you can send the value of the last range key to the client and use greater/less.

**Comment by guregu** [comment]
OK, I added a way to use LastEvaluatedKey. It works with Table.Get and Table.Scan. 

Here's an example. This scans the table but limits the results to 50. 
```
var items []myItem
key, err := table.Scan().SearchLimit(50).AllWithLastEvaluatedKey(&items)
```
You can then send `key` to the client (which is a [dynamo.PagingKey](https://godoc.org/github.com/guregu/dynamo#PagingKey)).

When you want to continue searching with that key, you use StartFrom:
```
key, err := table.Scan().StartFrom(key).SearchLimit(50).AllWithLastEvaluatedKey(&items)
```
Note that if you use filters and SearchLimit, you might get blank results but still get a valid LastEvaluatedKey, this is just how DynamoDB works.

**Comment by SAPessi** [comment]
Don't think [this method](https://github.com/guregu/dynamo/blob/master/scan.go#L122) should receive the ctx as a parameter.

**Comment by guregu** [comment]
Closing for now but let me know if you have any problems.

**Comment by guregu** [comment]
> Is there a way to turn this into a string that I can send through API

Yeah. One way is to JSON encode it, and then base64 encode the JSON if you want to put it in a URL. If you're returning JSON in your API you can add it to response/request structs and it should work

Something like this:

```go
type response struct{
    Data []myItem
    Next dynamo.PagingKey
}

var items []myItem
key, err := table.Scan().SearchLimit(50).AllWithLastEvaluatedKey(&items)

resp := response{Data: items, Next: key}
err = json.NewEncoder(w).Encode(resp)
```

I considered adding TextMarshaler to the PagingKey to automatically base64 encode it but I'm not sure if that'll break anything for people already using it. Maybe a good idea for v2.

**Comment by yuisofull** [comment]
> > Is there a way to turn this into a string that I can send through API
> 
> Yeah. One way is to JSON encode it, and then base64 encode the JSON if you want to put it in a URL. If you're returning JSON in your API you can add it to response/request structs and it should work
> 
> Something like this:
> 
> ```go
> type response struct{
>     Data []myItem
>     Next dynamo.PagingKey
> }
> 
> var items []myItem
> key, err := table.Scan().SearchLimit(50).AllWithLastEvaluatedKey(&items)
> 
> resp := response{Data: items, Next: key}
> err = json.NewEncoder(w).Encode(resp)
> ```
> 
> I considered adding TextMarshaler to the PagingKey to automatically base64 encode it but I'm not sure if that'll break anything for people already using it. Maybe a good idea for v2.

Thanks alot sir, I have written some functions to make the PagingKey turn into a string, I dont know if there are ways to do this more effectively (to hide unesscessary info like userID, postID):
```go
func Encode(key dynamo.PagingKey) *string {
	hashKey := base58.Encode([]byte(*key["UserID"].S))
	rangeKey := base58.Encode([]byte(*key["TweetID"].N))
	res := fmt.Sprintf("%s.%s", hashKey, rangeKey)
	return &res
}

func Decode(encoded string) (dynamo.PagingKey, error) {
	parts := strings.Split(encoded, ".")
	if len(parts) != 2 {
		return nil, fmt.Errorf("invalid paging key")
	}
	return dynamo.PagingKey{
		"UserID":  &dynamodb.AttributeValue{S: aws.String(string(base58.Decode(parts[0])))},
		"TweetID": &dynamodb.AttributeValue{N: aws.String(string(base58.Decode(parts[1])))},
	}, nil
}
```

**Comment by guregu** [comment]
That looks good to me. Keep in mind that if you use indexes the structure of the PagingKey will change (it will add extra keys for the primary keys of the index). If you know in advance which keys you need it's OK to omit them and add them back later like this. DynamoDB needs the key names to do its pagination unfortunately, the PagingKey is the same data as what DynamoDB's APIs call LastEvaluatedKey.
