### ISSUE TITLE
JSON colomns 

### ISSUE THREAD

**Issue by auriou** [guregu/dynamo#60]
Hello, 
I have columns with complex objects in json. 

Is it possible to serialize and deserialize these columns directly?

![image](https://user-images.githubusercontent.com/1873587/36947978-eff54cc8-1fd3-11e8-9470-abe995c30d9d.png)

**Comment by guregu** [comment]
Yes, that should work fine.

**Comment by auriou** [comment]
Could you show me an example, it does not work. thank you

**Comment by jney** [comment]
@auriou nested object can be stored "out of the box".
why do you make reference to json, do you want to store them as string?

**Comment by ngocketit** [comment]
Doesn't work for me either. Code example:
```
type appConfig struct {
	CdnBaseUrl          string `json:"cdnBaseUrl,omitempty"`
	PostMediaCdnPrefix  string `json:"postMediaCdnPrefix,omitempty"`
	UserAvatarCdnPrefix string `json:"userAvatarCdnPrefix,omitemtpy"`
}

type appConfigDocument struct {
	Pk     string    `dynamo:"pk"`
	Config appConfig `dynamo:"config"`
}
var config appConfigDocument
dbTable.Get("pk", appId).One(&config)
```

`config.Config` fields are all empty. Following is the data in DynamoDB table:

![Screenshot 2021-05-27 at 12 36 21](https://user-images.githubusercontent.com/1885269/119803493-2d803880-bee8-11eb-89d3-b88a12f99f56.png)

**Comment by ngocketit** [comment]
So using `AWSEncoding` works but not sure why it's needed. I inserted content to DynamoDB table manually from AWS console. Is that the reason?

```
dbTable.Get("pk", appId).One(dynamo.AWSEncoding(&config))
```

**Comment by ngocketit** [comment]
@guregu I totally missed that. Thanks a lot!
