### ISSUE TITLE
Cannot unmarshal results from Scan and Get to []map[string]interface{}

### ISSUE THREAD

**Issue by vladoohr** [guregu/dynamo#62]
Hi, here is the code snipped:

	var records []map[string]interface{}

	err := c.Scan().Filter("$ = ?", "email", "example@gmail.com").Consistent(true).All(&records)
	if err != nil {
		return err
	}
...

I am getting the following error:

"panic: reflect: call of reflect.Value.Set on zero Value\npanic(0x9c45a0, 0xc4202abb20)\n\t/usr/local/go/src/runtime/panic.go:489 +0x2cf\nreflect.flag.mustBeExported(0x0)\n\t/usr/local/go/src/reflect/value.go:209 +0x145\nreflect.Value.Set(0x9bd700, 0xc4202b8e90, 0x194, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/reflect/value.go:1346 +0x40\ngithub.com/guregu/dynamo.unmarshalReflect(0xc4204039a0, 0x9bd700, 0xc4202b8e90, 0x194, 0xc4202b8e90, 0x194)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/guregu/dynamo/decode.go:223 +0x1e5d\ngithub.com/guregu/dynamo.unmarshalItem(0xc4202d49c0, 0x97eb60, 0xc42009a0a8, 0x97eb60, 0xc42009a0a8)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/guregu/dynamo/decode.go:362 +0x826\ngithub.com/guregu/dynamo.unmarshalAppend(0xc4202d49c0, 0x974260, 0xc4202a5720, 0x0, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/guregu/dynamo/decode.go:380 +0x1d8\ngithub.com/guregu/dynamo.(*scanIter).NextWithContext(0xc4201b8c18, 0x7f158d224498, 0xc42020db00, 0x974260, 0xc4202a5720, 0xc4201b8c58)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/guregu/dynamo/scan.go:255 +0x2d3\ngithub.com/guregu/dynamo.(*Scan).AllWithLastEvaluatedKeyContext(0xc420402320, 0x7f158d224498, 0xc42020db00, 0x974260, 0xc4202a5720, 0x1, 0x0, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/guregu/dynamo/scan.go:136 +0xaf\ngithub.com/guregu/dynamo.(*Scan).All(0xc420402320, 0x974260, 0xc4202a5720, 0x0, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/guregu/dynamo/scan.go:110 +0x9e\ngithub.com/JormungandrK/backends.(*DynamoCollection).GetOne(0xc42010a028, 0xc4202d4120, 0x97b1e0, 0xc4202b8190, 0xc4200648a8, 0xc4200a5328)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/JormungandrK/backends/dynamodb.go:168 +0x5d2\ngithub.com/JormungandrK/backends.(*DynamoCollection).DeleteOne(0xc42010a028, 0xc4202d4120, 0xc4201b9020, 0xc4200a53a8)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/JormungandrK/backends/dynamodb.go:310 +0x12f\ngithub.com/JormungandrK/backends.(*DynamoCollection).Save(0xc42010a028, 0x9c0b80, 0xc420435260, 0x0, 0xc420318600, 0x3c, 0x3c, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/JormungandrK/backends/dynamodb.go:258 +0xce2\nmain.(*UserController).Create(0xc42020ad20, 0xc4202a2ff0, 0xc4202b20a0, 0xc420198e00)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/JormungandrK/user-microservice/user.go:82 +0x106\ngithub.com/JormungandrK/user-microservice/app.MountUserController.func1(0xd62d60, 0xc4202a2f60, 0xd62020, 0xc4203183c0, 0xc42022d300, 0xc42004b2b0, 0xc42004b2a8)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/JormungandrK/user-microservice/app/controllers.go:92 +0x11f\ngithub.com/goadesign/goa.(*Controller).MuxHandler.func1.1.1(0xd62d60, 0xc4202a2f60, 0xd62020, 0xc4203183c0, 0xc42022d300, 0x2, 0x2)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/service.go:309 +0xaa\ngithub.com/goadesign/goa/middleware.Recover.func1.1(0xd62d60, 0xc4202a2f60, 0xd62020, 0xc4203183c0, 0xc42022d300, 0x0, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/middleware/recover.go:37 +0xac\ngithub.com/goadesign/goa/middleware.ErrorHandler.func1.1(0xd62d60, 0xc4202a2f60, 0xd62020, 0xc4203183c0, 0xc42022d300, 0x2, 0x2)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/middleware/error_handler.go:21 +0x90\ngithub.com/goadesign/goa/middleware.LogRequest.func1.1(0xd62d60, 0xc4202a2f60, 0xd62020, 0xc4203183c0, 0xc42022d300, 0xc42025deb0, 0xd62d60)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/middleware/log_request.go:75 +0xe50\ngithub.com/goadesign/goa/middleware.RequestIDWithHeaderAndLengthLimit.func1.1(0xd62d60, 0xc4202a2e10, 0xd62020, 0xc4203183c0, 0xc42022d300, 0x0, 0xd62d60)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/middleware/request_id.go:63 +0x177\ngithub.com/goadesign/goa.(*Controller).MuxHandler.func1(0xd62360, 0xc4202f8620, 0xc42022d300, 0xc4202a2d80)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/service.go:342 +0x1f1\ngithub.com/goadesign/goa.(*mux).Handle.func1(0xd62360, 0xc4202f8620, 0xc42022d300, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/mux.go:69 +0x1b3\ngithub.com/dimfeld/httptreemux.(*TreeMux).ServeLookupResult(0xc420112000, 0xd62360, 0xc4202f8620, 0xc42022d300, 0xc8, 0xc4202a0820, 0x0, 0x0)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/dimfeld/httptreemux/router.go:245 +0x13d\ngithub.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc420112000, 0xd62360, 0xc4202f8620, 0xc42022d300)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/dimfeld/httptreemux/router.go:266 +0xef\ngithub.com/goadesign/goa.(*mux).ServeHTTP(0xc420106670, 0xd62360, 0xc4202f8620, 0xc42022d300)\n\t/home/vladimir/projects/jormungandr/microservices/src/github.com/goadesign/goa/mux.go:100 +0x4c\nnet/http.serverHandler.ServeHTTP(0xc4201591e0, 0xd62360, 0xc4202f8620, 0xc42022d300)\n\t/usr/local/go/src/net/http/server.go:2568 +0x92\nnet/http.(*conn).serve(0xc4203508c0, 0xd62ca0, 0xc420318100)\n\t/usr/local/go/src/net/http/server.go:1825 +0x612\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2668 +0x2ce\n"

I guess I am doing something wrong.

Thanks in advance.

**Comment by guregu** [comment]
Hello, thank you very much for your report. This was a bug in dynamo. I think I fixed it in 6335cf6.
Did you have NULL columns in your data? Please update the library and try again.

**Comment by vladoohr** [comment]
Now it works perfectly fine. I did have NULL columns. 

Thanks for the quick fix.
