### ISSUE TITLE
Question: attribute_not_exists

### ISSUE THREAD

**Issue by vladoohr** [guregu/dynamo#63]
Hello,

Is it possible to use attribute_not_exists for composite key? Example:

`err = c.Table.Put(av).If("attribute_not_exists($) AND attribute_not_exists($)", hashKey, rangeKey).Run()`

Thanks.

**Comment by guregu** [comment]
I'm not 100% sure, but...
I think this will work. However, I don't think it's necessary to check both. You can just check only the hash key (or only the range key) and it has the same effect.

**Comment by vladoohr** [comment]
Only to check for hash key was enough. Thanks
