### ISSUE TITLE
Set limit and offset for pagination

### ISSUE THREAD

**Issue by vladoohr** [guregu/dynamo#64]
Hello,

How to use this library for pagination? I want to set limit and offset plus if it is possible to order the results by some attribute.

Thanks in advance.

**Comment by guregu** [comment]
If you want ordered results, you need to use a table (or index) with a range key. You can use an offset by using the `dynamo.Greater` or `dynamo.Less` (depending on your desired order) when you use `.Range()`. You can use `.Limit()` to set the result size limit. You can change the order with `.Order()`. 

The general idea is that you pass the last result of your previous page to the next one, and get the next keys that are greater or less than it using the Range method. 

You can also paginate through unordered results with `.SearchLimit()`, `.StartWith()` and the LastEvaluatedKey methods but you will have to account for empty results etc. depending on how your application is set up.

**Comment by vladoohr** [comment]
Thanks.
