### ISSUE TITLE
Descriptive Errors?

### ISSUE THREAD

**Issue by cody1024d** [guregu/dynamo#65]
I came into a scenario where I had an object that contained a property for which I was trying to unmarshal (dynamoDB -> struct) into an incorrect type.  In my case, in the dynamoDB table, it was of type map (fat-fingered data entry earlier), but was defined as a slice within the code.

This was fairly hard to track down because of the error message I received from decode.go:

```
dynamo: unmarshal slice: B, L, BS, SS, NS are nil
```

I see where this is coming from within the decode file; is there anyway to improve this error, as to be more explicit?  I feel like these mismatched types is a fairly common error.

**Comment by guregu** [comment]
I've improved this a little, now the error will say something like: `dynamo: can't unmarshal map data into slice`. In the future, I would like to add the name of the erroneous property too.

**Comment by cody1024d** [comment]
@guregu Ok, sounds good!  If I have a chance, is a PR welcome?  I'm fairly unfamiliar with GoLang's reflection, but I'm sure I can figure it out, when I get a second.

**Comment by guregu** [comment]
PRs are welcome, I think it would be pretty straightforward and involve adding an extra parameter to the `unmarshalReflect` function. The encoding/decoding stuff is ugly so I don't blame anyone for not wanting to touch it, I'm happy to add mess it with myself too.
