### ISSUE TITLE
Multiple Types from Same Table?

### ISSUE THREAD

**Issue by cody1024d** [guregu/dynamo#66]
If I have a table in DynamoDB, say Animals, where I insert both cats and dogs, is there a best practice way of fetching both types, at once, into an Animal list?

For Example in a batched query, I just want to hydrate all of the animals, but ensure all their properties are initialized.  I know the following code won't work (how could it, without knowing what animal type you're trying to populate into), but am unsure of the best-practice way of doing this.

```
var ls []Animal
err := t.Batch("Id").Get(k...).All(&ls)
```

For reference, there is a property on every animal, called AnimalType that was meant to be used as a differentiator.  Do I first have to batch query to get the types, and then somehow populate my animals from there?

**Comment by guregu** [comment]
Hello, there isn't a super easy way to do this. One way would be something like this (untested, incomplete code):

```go
import (
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/guregu/dynamo"
)

type Animal interface {
	isAnimal()
}

type Dog struct {
	Id        string
	Something string
}

func (Dog) isAnimal() {}

type Cat struct {
	Id           string
	SomeCatThing string
}

func (Cat) isAnimal() {}

func getAnimals() ([]Animal, error) {
	var results []Animal
	var item map[string]*dynamodb.AttributeValue
	iter := table.Batch("Id").Get( /* IDs go here */ ).Iter()
	for iter.Next(&item) {
		animalType := item["AnimalType"]
		if animalType.S == nil {
			// error: no type
		}
		switch *animalType.S {
		case "Dog":
			var dog Dog
			err := dynamo.UnmarshalItem(item, &dog)
			// handle error
			results = append(results, dog)
		case "Cat":
			var cat Cat
			// same idea..
		}
	}
	return results, iter.Err()
}
```

The idea is that you first unmarshal it to `map[string]*dynamodb.AttributeValue` and inspect the raw values before you unmarshal it again to the correct type. Then you can do a type switch on Animal to figure out whether it's a Cat or a Dog.

**Comment by guregu** [comment]
I could make this easier by adding a way for complete DynamoDB items to unmarshal themselves (dynamo.Unmarshaler only works for individual attributes). Hmm... 🤔

**Comment by cody1024d** [comment]
@guregu Thanks for the advice (and for answering both of my issues I opened)!  Do you think there will be any considerable performance issues with the above, considering we're now unmarshalling the full object twice?  In my case it shouldn't be too many properties, for now, but it may grow in the future?  

I guess if this was a concern, instead of unmarshalling again, I could create an AttributeValue -> Cat and Attribute Value -> Dog function, that didn't use reflection, similar to what I'd do if I were using the straight dynamodb SDK.

**Comment by guregu** [comment]
There is a [fast path](https://github.com/guregu/dynamo/blob/1eac96337922d24cb810c5d647d761d25fb01554/decode.go#L328) for `map[string]*dynamodb.AttributeValue` which only assigns and doesn't involve reflection, so it will only actually unmarshal stuff once per item when you call `dynamo.UnmarshalItem()` manually.

**Comment by cody1024d** [comment]
@guregu Perfect!  Thanks again!

**Comment by cody1024d** [comment]
@guregu Hey sorry for an additional question.  Is it possible to NOT use the iterator syntax to map to attributed values?  Does dynamo support:

```go
var items []map[string]*dynamodb.AttributeValue
err := t.Batch("Id").Get(k...).All(&items)
```

The above syntax would help me leverage this inside of the GraphQL/DataLoader paradigm I'm using (in that I need to return the same number of results as keys that are passed in, and using the iterator syntax for this is yicky)

**Comment by guregu** [comment]
That should work. If it doesn't let me know because it's a bug.
