### ISSUE TITLE
nested struct

### ISSUE THREAD

**Issue by jney** [guregu/dynamo#72]
hi @guregu , I'm trying to store a complex structure into dynamodb. here is an overview of what i'm trying to achieve:

```go
type Event struct {
	Events []EventElement `dynamo:"events,set"`
	ID     string         `dynamo:"id"`
}

type EventElement struct {
	ID       string `dynamo:"string"`
	Items        []Item `dynamo:"items,set,omitempty"`
}

type Item struct {
	ID    string `dynamo:"id"`
	Price Price  `dynamo:"price"`
}

type Price struct {
	Amount   int    `dynamo:"amount"`
	Currency string `dynamo:"currency"`
}
```

You got the idea, i want to store `Event` which have many `EventElement`s, which have many `Item`s... etc.
How can i map such complex structure?
Thank you

**Comment by guregu** [comment]
Hello, you should be able to store an Event if you change remove the `set` option from `Event.Events` and `EventElement.Items`. DynamoDB sets can only be string, number, or bytes. It will get saved as a list instead. Let me know if it doesn't work.

**Comment by jney** [comment]
indeed. very helpful. thank you
