### ISSUE TITLE
create table if not exist

### ISSUE THREAD

**Issue by jney** [guregu/dynamo#73]
Is there a way to avoid having a error if table already exists ?

```
"ResourceInUseException: Cannot create preexisting table\n\tstatus code: 400, request id: 5cffe283-a803-4b6b-a0b8-220a30778498"
```

Thank you

**Comment by guregu** [comment]
The easiest way is to just try to create one and ignore that error message. You can use this type to figure out more information about AWS errors: https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/#Error

Something like (untested):
```go
if awsErr, ok := err.(awserror.Error); ok {
   if awsErr.Code() == "ResourceInUseException" {
      // ignore it...
   }
}
```
