### ISSUE TITLE
cannot marshal type map[string]int into a set

### ISSUE THREAD

**Issue by cbarraford** [guregu/dynamo#75]
Hello,
I have a struct where i have a numerical representation of various skills, but i get the error (at the bottom). Can you not use `map[string]int` as a set???

```
type Talent struct {
  Id              string         `json:"id"`
  Name            string         `json:"name"`
  LinkedInProfile string         `json:"linkedin_profile"`
  Skills          map[string]int `json:"skills" dynamo:",set"`
  CreatedAt       string         `json:"created_at"`
}
```

```
dynamo: cannot marshal type map[string]int into a set
```

**Comment by guregu** [comment]
Looks like you want a map, not a set. Take the `dynamo:",set"` part out and it will work. Check out the documents for the [Map](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes.Document.Map) and [Set](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes.SetTypes) data types.

**Comment by cbarraford** [comment]
@guregu thanks for getting back to me quickly. In the `README.md`, the example map is uses `dynamo:",set"` for its descriptor. should it say `map`? Is there a typo in the readme?

**Comment by guregu** [comment]
Using maps to represent sets is a trick you can do in Go. Let's say I want to store a set of unique strings. You can use a slice, `[]string`, but it doesn't guarantee uniqueness and you need to loop through it to test for membership. If you use a map instead like `map[string]struct{}` you can ensure uniqueness and easily test for membership. The `struct{}` is a totally empty value, it represents nothing and does not take up memory. This library supports both ways.

I agree that the readme is a bit confusing though, the example isn't very good at all.

**Comment by cbarraford** [comment]
ok, makes sense to me. Thanks again!
