### ISSUE TITLE
Marshalling `time.Time` as a number

### ISSUE THREAD

**Issue by LeoAdamek** [guregu/dynamo#83]
I'm trying to store `time.Time` values in Dynamo as numbers (unix timestamps) so I can use then as range keys.

I've created the following time with a Marshaller and Unmarshaller implementation:

````go
// Timestamp represents a time.Time value stored in DynamoDB as a number
type Timestamp struct {
	time.Time
}

// MarshalDynamoDBAttributeValue marshals the timestamp to an attribute value as a number
func (t *Timestamp) MarshalDynamoDBAttributeValue(v *dynamodb.AttributeValue) error {
	n := t.Unix()

	v.SetN(strconv.FormatInt(n, 10))
	return nil
}

// UnmarshalDynamoDBAttributeValue loads a Timestamp from a Dynamo DB Attribute Value
func (t *Timestamp) UnmarshalDynamoDBAttributeValue(v *dynamodb.AttributeValue) error {

	ts, err := strconv.ParseInt(*v.N, 10, 64)

	if err != nil {
		return err
	}

	t.Time = time.Unix(ts, 0)
	return nil
}
````

I then use this as a value in a struct:

````go
type Item struct {
    PartitionKey string `dynamo:"partition_key"`
    Timestamp Timestamp `dynamo:"timestamp"`
}
````

However, when marshaling an `Item` the resulting value is:

````json
{ "partition_key": { "S": "example"}, "timestamp": { "S": "2018-12-09T01:19:01.01"}}
````

However the expected value is:

````json
{"partition_key": {"S": "example"}, "timestamp": {"N": "1234567890"}}
````

It looks like the TextMarshaler of `time.Time` is being used intead of `dynamodb.Marshaller` ?

How do I ensure the correct marshaller is ued?

**Comment by guregu** [comment]
Hello, I think the problem is that `MarshalDynamoDBAttributeValue` is defined as a method of `*Timestamp`, but your struct doesn't use the pointer version. 

If you change your method to 
```go
func (t Timestamp) MarshalDynamoDBAttributeValue(v *dynamodb.AttributeValue) error {
```
or your struct to
```go
type Item struct {
    PartitionKey string `dynamo:"partition_key"`
    Timestamp *Timestamp `dynamo:"timestamp"`
}
```

it will work. 

But I think this is a bug/surprising behavior and I'd like to fix it if possible.
BTW you can accomplish the same thing by using [`dynamodbattribute.UnixTime`](https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/dynamodbattribute/#UnixTime) (notice how the encode method is defined with a non-pointer receiver)

**Comment by guregu** [comment]
Also, you can also use time.Time's default TextMarshaler as a range key just fine, if you're OK with having a string range key. It will be in the proper order. It may be worth considering that if you use UnixTime as a range key, you can only have one item per second and if you try to write two items in the same second, the first one will get overwritten. time.Time's TextMarshaler goes into fractional seconds so you don't have to worry about that.

**Comment by LeoAdamek** [comment]
@guregu - Changing the Marshaller implementation to a non-pointer receiver worked. I've additionally changed my implementation to use nanoseconds instead of seconds, so time-based collisions shouldn't be an issue as I can now have one item per nanosecond, per partition key value. I'm only storing timestamps for the current time so the limits to the value range shouldn't be an issue.

As for using textual time as a range key, while they may be correctly _ordered_ would it not cause issues with range expressions? i.e. GT, GTE, LT and LTE expressions?

In my example I'm storing time-based events for multiple series, where the series is the partition key, and the event timestamp is the range key, this way I can query a single series over a given time-span efficiently.

**Comment by LeoAdamek** [comment]
@guregu  - True, I've actually changed my application now to use RFC3339Nano for timestamps and then can still to ranges over the time-series data using this. Closing as not required.
