### ISSUE TITLE
Add User page missing "submit" button when the font is enlarged

### ISSUE THREAD

**Issue by greenleaf55** [guregu/dynamo#85]
When adding a user for a family, the "Add User" screen covers the whole screen, and there is no "submit" button even scrolling the page to the bottom. 
![screen shot 2018-12-26 at 9 48 11 pm](https://user-images.githubusercontent.com/18609666/50470630-1f6c0d80-0966-11e9-8e54-be4fcf11b342.png)

**Comment by guregu** [comment]
Wrong repo? 🙂

**Comment by greenleaf55** [comment]
Oops. Sorry about that.
________________________________
