### ISSUE TITLE
how to makes dynamodb table ondemand billing mode?

### ISSUE THREAD

**Issue by crynut84** [guregu/dynamo#87]
how to makes dynamodb table ondemand billing mode?

```
aws dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
    --billing-mode=PAY_PER_REQUEST
```
ref. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.Basics.html#WorkingWithTables.Basics.CreateTable

**Comment by guregu** [comment]
Sorry for the wait. I've added this in v1.2.0! Just use `OnDemand(true)` when creating a table.
