### ISSUE TITLE
Is batchDelete supported ?

### ISSUE THREAD

**Issue by jgweir** [guregu/dynamo#90]
Hi Guregu,

Was wondering if batch delete is supported, or do you support this via BatchWrite (with delete instructions?).

Thanks for any clarification.
Kind regards
James

**Comment by guregu** [comment]
Hello James, 
Batch delete is indeed supported using BatchWrite. You can also use write transactions (WriteTx) to delete up to 10 things at a time if you need transactions.

An example of using BatchWrite would be something like:
```go
_, err := table.Batch("ID", "Month").Write().
	Delete(dynamo.Keys{1, "2015-10"}, dynamo.Keys{42, "2015-12"}, dynamo.Keys{42, "1992-02"}).
	Run()

```
